import PDFDocument from 'pdfkit';
import { mockDb } from './mockDb.js';
import crypto from 'crypto';

export function generateAuditPackPDFStream(): PDFKit.PDFDocument {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  const tenant = mockDb.tenants[0];
  const controls = mockDb.controls;
  const auditLogs = mockDb.auditLogs;
  const evidenceList = mockDb.evidence;

  // Compute package cryptographic seal
  const packagePayload = JSON.stringify({ tenant, controls, auditLogs, evidenceList });
  const packageSealSHA256 = crypto.createHash('sha256').update(packagePayload).digest('hex');

  // Header Banner
  doc.fillColor('#0f172a').rect(0, 0, 595.28, 70).fill();
  doc.fillColor('#ffffff').fontSize(18).text('VETERINARY CARE COMPLIANCE AUDIT PACK', 40, 20);
  doc.fontSize(10).text(`Tenant: ${tenant.name} | License: ${tenant.license_number}`, 40, 44);

  doc.moveDown(3);

  // Metadata block
  doc.fillColor('#334155').fontSize(12).text(`Generated: ${new Date().toUTCString()}`);
  doc.fontSize(10).fillColor('#0284c7').text(`Cryptographic Package Seal (SHA-256): ${packageSealSHA256}`);
  doc.moveDown(1.5);

  // Controls Summary Table
  doc.fillColor('#0f172a').fontSize(14).text('1. Active Compliance Controls & Regulatory Mapping', { underline: true });
  doc.moveDown(0.5);

  controls.forEach((ctrl, i) => {
    const ob = mockDb.obligations.find(o => o.id === ctrl.obligation_id);
    doc.fontSize(10).fillColor('#1e293b').text(`${i + 1}. [${ctrl.control_code}] ${ctrl.title}`);
    doc.fontSize(9).fillColor('#64748b').text(`   Regulatory Obligation: ${ob ? ob.regulatory_body + ' (' + ob.code + ')' : 'Standard'}`);
    doc.fontSize(9).fillColor(ctrl.status === 'COMPLIANT' ? '#16a34a' : ctrl.status === 'NON_COMPLIANT' ? '#dc2626' : '#d97706')
       .text(`   Status: ${ctrl.status} | Risk Level: ${ctrl.risk_rating} | Last Tested: ${ctrl.last_tested_at ? ctrl.last_tested_at.split('T')[0] : 'N/A'}`);
    doc.moveDown(0.5);
  });

  doc.moveDown(1);

  // Evidence Lineage Table
  doc.fillColor('#0f172a').fontSize(14).text('2. Evidence Artifact Lineage & Cryptographic Hashes', { underline: true });
  doc.moveDown(0.5);

  evidenceList.forEach((ev, i) => {
    doc.fontSize(10).fillColor('#1e293b').text(`${i + 1}. Artifact: ${ev.file_name}`);
    doc.fontSize(9).fillColor('#64748b').text(`   Category: ${ev.category} | AI Model: ${ev.ai_model_version} | Confidence: ${(ev.ai_confidence * 100).toFixed(1)}%`);
    doc.fontSize(8).fillColor('#475569').text(`   SHA-256: ${ev.file_sha256}`);
    doc.fontSize(8).fillColor('#0369a1').text(`   Grounding: ${ev.ai_grounding_explanation}`);
    doc.moveDown(0.5);
  });

  doc.moveDown(1);

  // Decision Audit History
  doc.fillColor('#0f172a').fontSize(14).text('3. Human-in-the-Loop Decision & Override Audit History', { underline: true });
  doc.moveDown(0.5);

  auditLogs.forEach((log, i) => {
    doc.fontSize(10).fillColor('#1e293b').text(`${i + 1}. Reviewer: ${log.actor_name} (${log.actor_role})`);
    doc.fontSize(9).fillColor('#334155').text(`   Action: ${log.action} | Transition: ${log.previous_status} -> ${log.new_status} | Date: ${log.created_at}`);
    doc.fontSize(9).fillColor('#475569').text(`   Mandatory Rationale: "${log.reason}"`);
    doc.moveDown(0.5);
  });

  // Footer Certificate
  doc.moveDown(2);
  doc.fillColor('#0f172a').fontSize(10).text('OFFICIAL REGULATORY ATTESTATION', { align: 'center' });
  doc.fontSize(8).fillColor('#64748b').text('This document represents an unaltered, cryptographically sealed compliance pack generated by the Veterinary Care Compliance Evidence System.', { align: 'center' });

  doc.end();
  return doc;
}
